### ISSUE TITLE
New time format in aws-cli sso cache files causes crash

### ISSUE THREAD

**Issue by gerasym** [linaro-its/aws2-wrap#30]
New format seem to be 2021-01-21T23:08:40Z so when aws2-wrap tries to read the expiration time it crashes:

```
File "/usr/local/lib/python3.6/site-packages/aws2wrap/__init__.py", line 93, in retrieve_token_from_file
      expire_datetime = datetime.strptime(expires_at.replace("UTC", "+0000"), "%Y-%m-%dT%H:%M:%S%z")
    File "/usr/lib64/python3.6/_strptime.py", line 565, in _strptime_datetime
      tt, fraction = _strptime(data_string, format)
    File "/usr/lib64/python3.6/_strptime.py", line 362, in _strptime
      (data_string, format))
  ValueError: time data '2021-01-21T23:08:40Z' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

**Comment by pcolmer** [comment]
@gerasym 

Can you please confirm:

1. The version of AWS CLI you are using?
2. The version of aws2-wrap you are using?
3. An example of the command you are using, redacted if anything sensitive is present.

Thanks.

**Comment by gerasym** [comment]
Versions are
```
aws2-wrap==1.1.4
aws-cli/2.1.19 Python/3.7.3 Linux/4.15.0-1102-oem exe/x86_64.ubuntu.18 prompt/off
```
Command
```
aws2-wrap --profile profile_name terraform init
```
gives me this full traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/aws2-wrap", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/aws2wrap/__init__.py", line 246, in main
    grc_structure = get_role_credentials(profile)
  File "/usr/local/lib/python3.6/dist-packages/aws2wrap/__init__.py", line 123, in get_role_credentials
    sso_access_token = retrieve_token(sso_start_url, sso_region, profile_name)
  File "/usr/local/lib/python3.6/dist-packages/aws2wrap/__init__.py", line 108, in retrieve_token
    token = retrieve_token_from_file(cachefile, sso_start_url, sso_region)
  File "/usr/local/lib/python3.6/dist-packages/aws2wrap/__init__.py", line 93, in retrieve_token_from_file
    expire_datetime = datetime.strptime(expires_at.replace("UTC", "+0000"), "%Y-%m-%dT%H:%M:%S%z")
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2021-01-21T23:08:40Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

```

**Comment by gerasym** [comment]
aws-cli/2.1.20 has the same date format in sso cache file

**Comment by pcolmer** [comment]
Thanks, @gerasym 

I've upgraded my copy of AWS CLI to 2.1.20 and I'm seeing the same date format in my cache file but my copy of aws2-wrap is not complaining, so I'm just trying to figure out why.

**Comment by gerasym** [comment]
I removed cache files to relogin after i upgraded to 2.1.19 and 2.1.20

**Comment by pcolmer** [comment]
This is what I'm seeing on my system:

```
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> expiresAt="2021-01-21T23:30:56Z"
>>> from datetime import datetime, timezone
>>> datetime.strptime(expiresAt.replace("UTC", "+0000"), "%Y-%m-%dT%H:%M:%S%z")
datetime.datetime(2021, 1, 21, 23, 30, 56, tzinfo=datetime.timezone.utc)
```

It clearly works on my system, which isn't an excuse 😉. I'll keep digging.

**Comment by pcolmer** [comment]
> I removed cache files to relogin after i upgraded to 2.1.19 and 2.1.20

I've done the same and re-logged in. I'm definitely seeing "expiresAt" with a string that ends with "Z" but it doesn't break aws2-wrap on my system.

**Comment by pcolmer** [comment]
@gerasym Can you please confirm that you are using this with Python 3 and *not* Python 2?

**Comment by gerasym** [comment]
Maybe datetime was changed in python3.8.5 which you seem to run? because on 3.6 i can see 

```
python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> expiresAt="2021-01-21T23:30:56Z"
>>> from datetime import datetime, timezone
>>> datetime.strptime(expiresAt.replace("UTC", "+0000"), "%Y-%m-%dT%H:%M:%S%z")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2021-01-21T23:30:56Z' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

**Comment by pcolmer** [comment]
Thank you, @gerasym!

I can confirm it seems to be the version of Python. I'll work on a fix/workaround.

**Comment by pcolmer** [comment]
Hi @gerasym 

I've uploaded version 1.1.5 which should fix the problem. Can you update and give it a try for me, please?

**Comment by gerasym** [comment]
Hi @pcolmer 

Thank you very much, it works.
That was quick!
